-- ELIMIMNA LAS TABLAS DEL TURNERO y los STORE PROCEDURE
-----------------------------------------------------------------------------------------------------------------------------
-- ESTE QUERY ES PARA ELIMINAR LO GENERADO CON NOMENCLAUTURA  JARDIN DEL PILAR
-----------------------------------------------------------------------------------------------------------------------------
-- BORRA EL TURNERO POR COMPLETO.

--ACA ELIMINO LAS TABLAS PROPIAS DEL DESARROLLO DE PQ DENTRO DEL DICCIONARIO
/*USE [Diccionario_048006_003]
GO

DROP TABLE users
DROP TABLE personal_access_tokens
DROP TABLE JDP_Empresa
DROP TABLE JDP_menus
DROP TABLE JDP_rolatributo
DROP TABLE JDP_rol
DROP TABLE JDP_permiso
DROP TABLE JDP_rutas
DROP TABLE dxtemas
*/
-- ACA ELIMINO LAS TABLAS PROPIAS DEL TURNERO EN SI MISMO
USE [JDP_DESARROLLO]
GO

DROP table JDP_TUR_ESTADO_TURNO
drop table JDP_TUR_ESTADOS_GRILLA
DROP TABLE JDP_TUR_FLUJO_ESTADO_TURNO
DROP TABLE JDP_TUR_HORARIOS_UN_SERVICIO
DROP TABLE JDP_TUR_MAILS_CCO
DROP TABLE JDP_TUR_TIPO_ESTADOS_TURNO
DROP TABLE JDP_TUR_UN_SER_ROL
DROP TABLE JDP_TUR_USUARIO_SECTOR
DROP TABLE JDP_TUR_DEF_FLUJO_ESTADO
DROP TABLE JDP_TUR_ROLES_USUARIOS
DROP TABLE JDP_TUR_TIPO_ROLES
DROP TABLE JDP_TUR_UNIDAD_SERVICIOS_ADICIONALES
DROP table JDP_TUR_TIPO_UNIDAD_SERVICIOS_ADICIONALES
drop table JDP_TUR_TURNOS
drop table JDP_TUR_SERVICIO_UNIDAD_NEGOCIO
drop table JDP_TUR_SECTOR_SUCURSAL
drop table JDP_TUR_TIPO_SERVICIOS_ADICIONALES
drop table JDP_TUR_SERVICIO
DROP table JDP_TUR_UNIDAD_NEGOCIO
DROP table JDP_TUR_SUCURSAL
DROP table JDP_TUR_TIPO_SUCURSAL
DROP table JDP_TUR_BLOQUEOS_UN_SERVICIO
DROP table JDP_TUR_MAILSENVIADO
DROP TABLE JDP_TUR_WHATSAPPENVIADO

-- ACA ELIMINO LOS STORE PROCEDURES PROPIOS DEL TURNERO EN SI MISMO
USE [JDP_DESARROLLO]
GO
DROP PROCEDURE JDP_TUR_SpaAgregaRolesUsuarios
DROP PROCEDURE JDP_TUR_SpClienteCRM
DROP PROCEDURE JDP_TUR_SpClienteCRMFiltrado
DROP PROCEDURE JDP_TUR_SpEnviaCorreo
DROP PROCEDURE JDP_TUR_SpEnviaWS
DROP PROCEDURE JDP_TUR_SpGrabarRolesUsuarios
DROP PROCEDURE JDP_TUR_SpGrabarTurno
DROP PROCEDURE JDP_TUR_SpGrillaServiciosAdicionales
DROP PROCEDURE JDP_TUR_SpGrillaTurnos2
DROP PROCEDURE JDP_TUR_SpHorariosInhablitados
DROP PROCEDURE JDP_TUR_SpPresupuestos
DROP PROCEDURE JDP_TUR_SpPresupuestosVersion
DROP PROCEDURE JDP_TUR_SPSectoresHabilitados
DROP PROCEDURE JDP_TUR_SpServicio
DROP PROCEDURE JDP_TUR_SpSucursal
DROP PROCEDURE JDP_TUR_SPSucursalesHabilitadas
DROP PROCEDURE JDP_TUR_SpTipo_Estados_Turno_Habilitados
DROP PROCEDURE JDP_TUR_SpTipoEstadosTurno
DROP PROCEDURE JDP_TUR_SpTipoSucursal
DROP PROCEDURE JDP_TUR_SpTurno_Unidad_Servicios_adicionales
DROP PROCEDURE JDP_TUR_SpTurnosInhablitados
DROP PROCEDURE JDP_TUR_SpTurnosOcupados
DROP PROCEDURE JDP_TUR_SpUnidad
DROP PROCEDURE JDP_TUR_SPValidarTurno
DROP PROCEDURE JDP_TUR_SpBloqueaSalas
DROP PROCEDURE JDP_TUR_SpGrillaTurnosCompleta